apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: nexus
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: {{.Values.nexus.port}}
    - name: docker
      protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 8086