apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: jenkins
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{.Values.jenkins.port}}
    - name: mongo
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 8082
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 3306
