apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - name: sonarqube
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: {{.Values.sonarqube.port}}
    - name: adminer
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{.Values.adminer.port}}
